import {z} from 'zod';
import {body,identity,ensureRoot,authorize,db,uid,now,ok,fail,HttpError,auditStatement,limit} from '@/lib/server';
import {stages} from '@/lib/registry';
const schema=z.object({name:z.string().trim().min(2).max(160),organization:z.string().trim().min(2).max(200),email:z.union([z.string().email().max(200),z.literal('')]).default(''),phone:z.string().max(40).default(''),sector:z.string().max(80),product:z.string().min(1).max(150),intent:z.string().max(100),requirements:z.string().min(3).max(4000),consent:z.literal(true),marketing:z.boolean().default(false),photoConsent:z.boolean().default(false),locale:z.enum(['en','bn']).default('en'),requestKey:z.string().uuid(),tenant_id:z.string().max(80).optional(),country:z.string().max(100).default('Bangladesh'),timeline:z.string().max(100).default(''),users:z.string().max(200).default(''),systems:z.string().max(500).default(''),budget:z.string().max(150).default(''),channel:z.string().max(30).default('Email'),source:z.string().max(100).default('Website'),event:z.string().max(200).default(''),owner:z.string().max(120).default(''),nextAction:z.string().max(100).default('Review enquiry'),due:z.string().max(30).default(''),university:z.string().max(200).default(''),programme:z.string().max(200).default(''),skills:z.string().max(500).default(''),portfolio:z.string().max(400).default(''),availability:z.string().max(200).default(''),attribution:z.record(z.string().max(150)).default({})});
export async function POST(req:Request){try{const parsed=schema.safeParse(await body(req));if(!parsed.success)throw new HttpError(400,'Please check required fields, email format and permissions.');const x=parsed.data;if(!x.email&&!x.phone)throw new HttpError(400,'Provide an email or phone number.');const user=await identity();await limit(req,user?.id||'intake',user?100:15);let tenant='daffodil';if(x.tenant_id){await authorize(x.tenant_id,'leads',true);tenant=x.tenant_id;}await ensureRoot();const old=await db().prepare('SELECT id,reference,tenant_id FROM leads WHERE tenant_id=? AND request_key=?').bind(tenant,x.requestKey).first();if(old)return ok({...old,repeated:true});
const id=uid(),ref='DAI-'+id.slice(0,8).toUpperCase(),stamp=now(),due=x.tenant_id&&/^\d{4}-\d{2}-\d{2}$/.test(x.due)?x.due:new Date(Date.now()+86400000).toISOString().slice(0,10);
const details=JSON.stringify({...x,requestKey:undefined,consentAt:stamp,consentVersion:'dai-privacy-v1',marketingAt:x.marketing?stamp:null,servicePermission:true});
const writes=[db().prepare("INSERT INTO leads (id,tenant_id,reference,request_key,submitted_by,name,organization,email,phone,sector,product,intent,stage,owner,due,source,consent,marketing,photo_consent,locale,details,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'New',?,?,?,?,?,?,?,?,?,?)").bind(id,tenant,ref,x.requestKey,user?.id||null,x.name,x.organization,x.email.toLowerCase(),x.phone,x.sector,x.product,x.intent,x.tenant_id&&x.owner?x.owner:'Unassigned',due,x.tenant_id?x.source:'Website',1,x.marketing?1:0,x.photoConsent?1:0,x.locale,details,stamp,stamp),db().prepare("INSERT INTO outbox (id,tenant_id,lead_id,status,attempts,updated_at) VALUES (?,?,?,'Pending',0,?)").bind(uid(),tenant,id,stamp),auditStatement(tenant,user?.email||'Public enquiry','enquiry.created',id,'Consented enquiry '+ref)];
if(x.intent==='Student application'||x.intent==='Support request'){const kind=x.intent==='Student application'?'students':'tickets';const payload=kind==='students'?{title:x.name,leadRef:ref,institution:x.university||x.organization,programme:x.programme,email:x.email,skills:x.skills,portfolio:x.portfolio,availability:x.availability,status:'Applied'}:{title:x.requirements.slice(0,100),leadRef:ref,contact:x.name,email:x.email,product:x.product,description:x.requirements,status:'New'};writes.push(db().prepare('INSERT INTO records (id,tenant_id,kind,title,payload,created_by,updated_by,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,1,?,?)').bind(uid(),tenant,kind,payload.title,JSON.stringify(payload),user?.id||'public',user?.id||'public',stamp,stamp));}
await db().batch(writes);return ok({id,reference:ref,tenant_id:tenant},201);}catch(e){return fail(e)}}
export async function GET(req:Request){try{const tenant=new URL(req.url).searchParams.get('tenant')||'daffodil';await authorize(tenant,'leads');const rows=await db().prepare('SELECT * FROM leads WHERE tenant_id=? ORDER BY created_at DESC LIMIT 1000').bind(tenant).all();return ok({leads:rows.results});}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{const x=await body(req);if(!stages.includes(x.stage))throw new HttpError(400,'Invalid stage');const {user}=await authorize(String(x.tenant_id),'leads',true);const lead=await db().prepare('SELECT * FROM leads WHERE tenant_id=? AND id=?').bind(x.tenant_id,x.id).first();if(!lead)throw new HttpError(404,'Enquiry not found');const owner=String(x.owner||lead.owner).slice(0,120),due=String(x.due||lead.due).slice(0,30);await db().batch([db().prepare('UPDATE leads SET stage=?,owner=?,due=?,updated_at=? WHERE tenant_id=? AND id=?').bind(x.stage,owner,due,now(),x.tenant_id,x.id),auditStatement(x.tenant_id,user.email,'enquiry.updated',x.id,'Stage: '+lead.stage+' → '+x.stage)]);return ok({saved:true});}catch(e){return fail(e)}}
