'use client';
import { useRef,useState } from 'react';
import { CheckCircle2,ArrowUpRight,Loader2,Camera,Upload,ScanLine } from 'lucide-react';
import { Field,Picker,Tick } from './form-controls';
import { Lang,pick,products } from '@/lib/catalog';
export function ContactForm({lang='en',intent='Book a demo',product='',tenantId='',operator=false,onSaved}:{lang?:Lang;intent?:string;product?:string;tenantId?:string;operator?:boolean;onSaved?:()=>void}){
 const t=(e:string,b:string)=>pick(lang,e,b);
 const requestKey=useRef('');
 const [form,setForm]=useState<Record<string,string>>({name:'',organization:'',email:'',phone:'',sector:'Industry',product,intent,country:'Bangladesh',timeline:'Exploring options',users:'',systems:'',requirements:'',channel:'Email',event:operator?'Bangladesh Innovation Fair 2026':'',owner:'',nextAction:'Demo',due:'',university:'',programme:'',skills:'',portfolio:'',availability:'',budget:'Scope first',source:operator?'Expo':'Website'});
 const [consent,setConsent]=useState(false),[marketing,setMarketing]=useState(false),[photoConsent,setPhotoConsent]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[card,setCard]=useState<File|null>(null),[photo,setPhoto]=useState<File|null>(null),[ocr,setOcr]=useState('');
 const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const student=form.intent==='Student application';
 const chooser=(key:string,label:string,options:string[])=> <div className="field"><span className="field-label">{label}</span><Picker value={form[key]} onChange={v=>update(key,v)} options={options} label={label}/></div>;
 async function scan(){if(!card||!consent){setOcr(t('Select a card image and confirm permission to process contact details first.','আগে কার্ডের ছবি ও যোগাযোগের তথ্য ব্যবহারের সম্মতি দিন।'));return;}setOcr(t('Reading card…','কার্ড পড়া হচ্ছে…'));try{const body=new FormData();body.append('file',card);body.append('tenant_id',tenantId);const r=await fetch('/api/ocr',{method:'POST',body});const d=await r.json() as Record<string,any>;if(!r.ok)throw new Error(d.error);const text=String(d.text||'');const email=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]||'';const phone=text.match(/\+?[\d][\d ()-]{7,18}\d/)?.[0]||'';setForm(f=>({...f,email:email||f.email,phone:phone||f.phone}));setOcr(t('Review extracted email and phone before saving.','সংরক্ষণের আগে ইমেইল ও ফোন যাচাই করুন।')+' '+text.slice(0,600));}catch(e){setOcr(t('Automatic card reading is not connected. Enter or verify the contact details below; the card can still be attached.','স্বয়ংক্রিয় কার্ড পাঠ চালু নেই। নিচে তথ্য লিখুন বা যাচাই করুন; কার্ড সংযুক্ত করা যাবে।'));}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!consent){setError(t('Please confirm permission to use these details for this request.','এই অনুরোধের তথ্য ব্যবহারের সম্মতি দিন।'));return;}if(!form.product){setError(t('Please select a product or service.','পণ্য বা সেবা বেছে নিন।'));return;}if(photo&&!photoConsent){setError(t('A separate photo permission is required.','ছবির জন্য আলাদা সম্মতি প্রয়োজন।'));return;}setBusy(true);
 try{if(!requestKey.current)requestKey.current=crypto.randomUUID();const query=new URLSearchParams(window.location.search);const attribution=Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,(query.get(k)||'').slice(0,150)]));const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,tenant_id:tenantId,consent,marketing,photoConsent,locale:lang,attribution,requestKey:requestKey.current})});const d=await r.json() as Record<string,any>;if(!r.ok)throw new Error(d.error||'Unable to save');let attachmentFailed=false;
 for(const [kind,file] of [['card',card],['photo',photo]] as const){if(file){const body=new FormData();body.append('file',file);body.append('record_id',d.id);body.append('tenant_id',d.tenant_id);body.append('kind',kind);const upload=await fetch('/api/files',{method:'POST',body});if(!upload.ok)attachmentFailed=true;}}
 requestKey.current='';setSuccess(d.reference);if(attachmentFailed)setError(t('The request was saved, but an attachment could not be uploaded. Add it later from the workspace.','অনুরোধ সংরক্ষিত হয়েছে; একটি সংযুক্তি আপলোড হয়নি। পরে কর্মক্ষেত্র থেকে যোগ করুন।'));onSaved?.();
 }catch(e){setError(t('Could not save. Your information is still here. Check your connection and try again.','সংরক্ষণ হয়নি। আপনার তথ্য এখানে আছে। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।')+' '+(e instanceof Error?e.message:''));}finally{setBusy(false);}}
 if(success)return <div className="form-success" role="status"><CheckCircle2 size={34}/><h3>{t('Your request is recorded.','আপনার অনুরোধ সংরক্ষিত হয়েছে।')}</h3><p>{t('Your reference','আপনার রেফারেন্স')}: <strong>{success}</strong></p><p>{t('Our team can now review your requirements and arrange the next step.','আমাদের দল আপনার প্রয়োজন পর্যালোচনা করে পরবর্তী পদক্ষেপ নেবে।')}</p>{error&&<p className="form-error">{error}</p>}<button className="btn btn-outline" onClick={()=>{setSuccess('');setError('');setForm(f=>({...f,name:'',email:'',phone:'',organization:'',requirements:''}));setConsent(false);setMarketing(false);setPhoto(null);setCard(null);setPhotoConsent(false);}}>{t('Record another enquiry','আরেকটি অনুসন্ধান লিখুন')}</button></div>;
 return <form onSubmit={submit} className="form-grid">
 {operator&&<div className="field full capture-box"><div className="icon-heading"><Camera size={20}/><strong>{t('Capture a conversation','আলোচনার তথ্য সংগ্রহ')}</strong></div><p>{t('Ask for permission, scan a card, then verify the details together. A visitor photo is optional.','সম্মতি নিয়ে কার্ড স্ক্যান করুন এবং তথ্য যাচাই করুন। দর্শনার্থীর ছবি ঐচ্ছিক।')}</p><div className="upload-grid"><label className="file-control"><Upload size={18}/>{t('Business card','ব্যবসায়িক কার্ড')}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setCard(e.target.files?.[0]||null)}/></label><label className="file-control"><Camera size={18}/>{t('Optional photo','ঐচ্ছিক ছবি')}<input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label></div>{card&&<button type="button" className="text-link" onClick={scan}><ScanLine size={16}/>{t('Read card & review','কার্ড পড়ে যাচাই')}</button>}{ocr&&<p className="status-text">{ocr}</p>}</div>}
 <Field label={t('Full name','পূর্ণ নাম')} value={form.name} onChange={v=>update('name',v)} required/>
 <Field label={t('Organization / institution','প্রতিষ্ঠান')} value={form.organization} onChange={v=>update('organization',v)} required/>
 <Field label={t('Email address','ইমেইল')} type="email" value={form.email} onChange={v=>update('email',v)} required={!form.phone}/>
 <Field label={t('Phone / WhatsApp','ফোন / হোয়াটসঅ্যাপ')} type="tel" value={form.phone} onChange={v=>update('phone',v)} required={!form.email} placeholder="+880"/>
 {chooser('sector',t('I represent','আমি প্রতিনিধিত্ব করছি'),['Industry','Academia','Government','Student','Partner','Media','Other'])}
 {chooser('intent',t('How can we help?','কীভাবে সাহায্য করতে পারি?'),['Book a demo','Request a quotation','Business enquiry','Institutional pilot','Government consultation','Student application','Research partnership','Channel partnership','Support request','Media enquiry'])}
 {chooser('product',t('Product / service','পণ্য / সেবা'),[...products.map(p=>p.name),'AI consultancy','AI Product Hub','Custom AI / API integration','AI infrastructure','AI marketing','Other / Help me choose'])}
 {chooser('timeline',t('Desired timeline','সম্ভাব্য সময়'),['Within 2 weeks','Within 1 month','Within 3 months','Exploring options'])}
 <Field label={t('Country','দেশ')} value={form.country} onChange={v=>update('country',v)} required/>
 <Field label={t('Expected users / locations','সম্ভাব্য ব্যবহারকারী / শাখা')} value={form.users} onChange={v=>update('users',v)} placeholder={t('e.g. 250 users, 3 campuses','যেমন ২৫০ ব্যবহারকারী, ৩ ক্যাম্পাস')}/>
 {chooser('budget',t('Budget approach','বাজেটের ধরন'),['Scope first','Budget allocated','Budget approval needed','Grant / funded project'])}
 {chooser('channel',t('Preferred contact channel','পছন্দের যোগাযোগ মাধ্যম'),['Email','Phone','WhatsApp'])}
 <Field label={t('Existing systems & integrations','বিদ্যমান ব্যবস্থা ও সংযোগ')} full value={form.systems} onChange={v=>update('systems',v)} placeholder="Odoo, ERP, LMS, HR, APIs…"/>
 {student&&<><Field label={t('University / college','বিশ্ববিদ্যালয় / কলেজ')} value={form.university} onChange={v=>update('university',v)} required/><Field label={t('Programme & semester','বিষয় ও সেমিস্টার')} value={form.programme} onChange={v=>update('programme',v)}/><Field label={t('Skills & interests','দক্ষতা ও আগ্রহ')} value={form.skills} onChange={v=>update('skills',v)}/><Field label={t('Portfolio / GitHub URL','পোর্টফোলিও / GitHub URL')} type="url" value={form.portfolio} onChange={v=>update('portfolio',v)}/><Field label={t('Availability & credit preference','সময় ও ক্রেডিটের পছন্দ')} value={form.availability} onChange={v=>update('availability',v)} full/></>}
 <Field label={t('What would you like to achieve?','আপনি কী অর্জন করতে চান?')} type="textarea" full required value={form.requirements} onChange={v=>update('requirements',v)} maxLength={4000} placeholder={t('Describe the problem, desired outcome, demo or support you need.','সমস্যা, কাঙ্ক্ষিত ফলাফল, ডেমো বা সহায়তার প্রয়োজন লিখুন।')}/>
 {operator&&<><Field label={t('Event / campaign','ইভেন্ট / ক্যাম্পেইন')} value={form.event} onChange={v=>update('event',v)}/><Field label={t('Staff member handling the conversation','আলোচনার দায়িত্বে স্টাফ')} value={form.owner} onChange={v=>update('owner',v)}/>{chooser('nextAction',t('Next action','পরবর্তী কাজ'),['Demo','Quotation','Call','Pilot discussion','Send information','Student review','Support follow-up'])}<Field label={t('Follow-up date','ফলোআপের তারিখ')} type="date" value={form.due} onChange={v=>update('due',v)}/></>}
 <Tick checked={consent} onChange={setConsent}>{t(operator?'The person has agreed to record these details and receive a response to this enquiry.':'I agree to the use of these details to respond to my enquiry.','এই তথ্য সংরক্ষণ ও অনুসন্ধানের উত্তর দেওয়ার জন্য সম্মতি দেওয়া হয়েছে।')} <a href="/privacy" className="underline">{t('Privacy & choices','গোপনীয়তা ও পছন্দ')}</a></Tick>
 {photo&&<Tick checked={photoConsent} onChange={setPhotoConsent}>{t('The person separately agrees to attach this photo for this enquiry. This does not permit publication or facial recognition.','এই অনুসন্ধানে ছবি সংযুক্ত করতে ব্যক্তির আলাদা সম্মতি রয়েছে। প্রকাশ বা মুখ শনাক্তকরণের অনুমতি নয়।')}</Tick>}
 <Tick checked={marketing} onChange={setMarketing}>{t('Optional: send relevant product news and invitations. I can withdraw this choice.','ঐচ্ছিক: প্রাসঙ্গিক পণ্যের খবর ও আমন্ত্রণ পাঠান। আমি সম্মতি প্রত্যাহার করতে পারি।')}</Tick>
 {error&&<div className="form-error" role="alert">{error}</div>}
 <div className="form-actions"><button className="btn btn-primary" type="submit" disabled={busy}>{busy?<Loader2 className="animate-spin" size={18}/>:null}{busy?t('Saving…','সংরক্ষণ হচ্ছে…'):t(operator?'Save enquiry':'Send enquiry',operator?'অনুসন্ধান সংরক্ষণ':'অনুসন্ধান পাঠান')}<ArrowUpRight size={17}/></button><span className="status-text">{t('Required fields are marked *','* চিহ্নিত তথ্য প্রয়োজন')}</span></div>
 </form>
}
