export type Lang='en'|'bn';
export const pick=(lang:Lang,en:string,bn:string)=>lang==='bn'?bn:en;
export const products=[
{id:'perfect-hr',name:'Perfect HR',category:['People & performance','মানুষ ও কর্মদক্ষতা'],icon:'users',tint:'#e7edf3',color:'#405973',stage:['AI capability roadmap','এআই সক্ষমতার রোডম্যাপ'],summary:['Connect people, performance and accountability. Bring everyday HR and your next generation of workforce intelligence together.','মানবসম্পদ, কর্মদক্ষতা ও জবাবদিহিতা একসাথে। দৈনন্দিন এইচআর-এর সঙ্গে ভবিষ্যতের কর্মী বিশ্লেষণ যুক্ত করুন।'],description:['A workforce platform spanning recruitment, attendance, payroll and performance. The next phase connects position intelligence, career development and human-reviewed AI with LeadershipOS.','নিয়োগ, উপস্থিতি, বেতন ও কর্মদক্ষতা ব্যবস্থাপনার প্ল্যাটফর্ম। পরবর্তী ধাপে পদভিত্তিক বিশ্লেষণ, ক্যারিয়ার উন্নয়ন ও মানুষের পর্যালোচনায় এআই যুক্ত হবে LeadershipOS-এর সাথে।'],audiences:['Industry','Government','Academia'],features:[['HR operations','কর্মী ব্যবস্থাপনা','Discuss attendance, leave, employee records and payroll scope.','উপস্থিতি, ছুটি, কর্মীর রেকর্ড ও বেতন ব্যবস্থাপনা।'],['Recruitment & growth','নিয়োগ ও উন্নয়ন','Map hiring, role requirements and staff development to measurable outcomes.','নিয়োগ, পদের চাহিদা ও দক্ষতা উন্নয়নকে পরিমাপযোগ্য ফলাফলের সাথে যুক্ত করুন।'],['Workforce intelligence','কর্মী বিশ্লেষণ','Roadmap: KPI evidence, position intelligence, PLCAS and Career GPS.','রোডম্যাপ: কেপিআই প্রমাণ, পদভিত্তিক বিশ্লেষণ, PLCAS ও Career GPS।'],['Connected leadership','সমন্বিত নেতৃত্ব','Planned API links to Perfect HR, LeadershipOS and Central MIS retain human authority.','পরিকল্পিত API সংযোগে LeadershipOS ও Central MIS-এর সাথে মানুষের সিদ্ধান্তের কর্তৃত্ব বজায় থাকবে।']],source:'https://perfecthr.net/',readiness:['Existing HR scope and new AI roadmap must be confirmed module by module during discovery. No release or compliance certification is implied.','বিদ্যমান এইচআর ও নতুন এআই ফিচার প্রতিটি মডিউল অনুযায়ী যাচাই করতে হবে।'],kpi:['Time to hire · payroll accuracy · review completion','নিয়োগের সময় · বেতনের নির্ভুলতা · পর্যালোচনা সম্পন্ন']},
{id:'ai-professor',name:'AI Professor',category:['Teaching & learning','শিক্ষাদান ও শেখা'],icon:'graduation',tint:'#eef1f9',color:'#5776a1',stage:['Controlled pilot','নিয়ন্ত্রিত পাইলট'],summary:['Give educators more room to teach. Explore AI-assisted learning, course content and formative assessment.','শিক্ষকদের শিক্ষাদানে আরও সময় দিন। এআই সহায়ক শিক্ষা, কোর্স কনটেন্ট ও মূল্যায়ন অন্বেষণ করুন।'],description:['AI Professor supports education with quizzes, assignments, content conversations, feedback, presentation and audio learning workflows. Academic decisions remain with the institution and teacher.','কুইজ, অ্যাসাইনমেন্ট, পাঠ্যবিষয়ক আলোচনা, ফিডব্যাক, প্রেজেন্টেশন ও অডিও শিক্ষায় AI Professor সহায়তা করে। একাডেমিক সিদ্ধান্ত শিক্ষক ও প্রতিষ্ঠানের হাতে থাকে।'],audiences:['Students','Academia'],features:[['Teaching preparation','পাঠ প্রস্তুতি','Explore assisted lesson content, summaries and presentations.','পাঠের কনটেন্ট, সারসংক্ষেপ ও প্রেজেন্টেশন তৈরিতে সহায়তা।'],['Learning support','শেখার সহায়তা','Content-based conversations and audio learning for students.','শিক্ষার্থীদের জন্য পাঠভিত্তিক আলোচনা ও অডিও শিক্ষা।'],['Assessment support','মূল্যায়ন সহায়তা','Quiz and assignment drafts reviewed by the responsible teacher.','দায়িত্বপ্রাপ্ত শিক্ষকের পর্যালোচনায় কুইজ ও অ্যাসাইনমেন্ট।'],['Academic governance','একাডেমিক নিয়ন্ত্রণ','The expanded reference architecture is pending ratification; approved material and human review are required.','বিস্তৃত স্থাপত্য অনুমোদনের অপেক্ষায়; অনুমোদিত উপকরণ ও মানুষের পর্যালোচনা প্রয়োজন।']],source:'https://daffodilsoft.com/product/ai-professor/',readiness:['Controlled pilot scope. The expanded 14-component academic AI architecture requires ratification and release evidence.','নিয়ন্ত্রিত পাইলটের সীমা প্রযোজ্য। বিস্তৃত ১৪ অংশের এআই স্থাপত্যে অনুমোদন ও প্রমাণ প্রয়োজন।'],kpi:['Teacher preparation time · learner engagement · reviewed output quality','শিক্ষকের প্রস্তুতির সময় · শিক্ষার্থীর অংশগ্রহণ · পর্যালোচিত মান']},
{id:'eduvas',name:'Eduvas',category:['Connected institutions','সমন্বিত শিক্ষা প্রতিষ্ঠান'],icon:'building',tint:'#fcf2e4',color:'#a1783f',stage:['Product + AI roadmap','পণ্য ও এআই রোডম্যাপ'],summary:['Bring the campus together. Connect admissions, academics, finance and the people behind every student journey.','এক প্ল্যাটফর্মে পুরো ক্যাম্পাস। ভর্তি, শিক্ষা কার্যক্রম, অর্থ ও শিক্ষার্থীর যাত্রার সকল মানুষকে যুক্ত করুন।'],description:['An education management portfolio for schools and universities, with configurable institutional workflows. The unified AI and omnichannel blueprint extends the existing platform through phased implementation.','স্কুল ও বিশ্ববিদ্যালয়ের জন্য কনফিগারযোগ্য শিক্ষা ব্যবস্থাপনা। সমন্বিত এআই ও বিভিন্ন চ্যানেলের ব্লুপ্রিন্ট ধাপে ধাপে বিদ্যমান প্ল্যাটফর্মকে প্রসারিত করে।'],audiences:['Students','Academia'],features:[['Admissions & student life','ভর্তি ও শিক্ষার্থী জীবন','Admissions, student records, counselling and role-based portals.','ভর্তি, শিক্ষার্থীর রেকর্ড, কাউন্সেলিং ও ভূমিকা অনুযায়ী পোর্টাল।'],['Academics & outcomes','একাডেমিক ফলাফল','Courses, timetables, examinations and outcome-based education scope.','কোর্স, রুটিন, পরীক্ষা ও ফলাফলভিত্তিক শিক্ষা।'],['Finance & operations','অর্থ ও পরিচালনা','Fees, accounts, HR, assets and institutional operations.','ফি, হিসাব, এইচআর, সম্পদ ও প্রাতিষ্ঠানিক পরিচালনা।'],['Integrated experience','সমন্বিত অভিজ্ঞতা','LMS and AI-channel integrations follow the agreed institution-specific scope.','প্রতিষ্ঠানভিত্তিক পরিকল্পনা অনুযায়ী LMS ও এআই চ্যানেলের সংযোগ।']],source:'https://daffodilsoft.com/product/eduvas-university/',readiness:['Existing school/university products; expanded unified AI capabilities are being implemented. Confirm deployment-specific availability.','বিদ্যমান স্কুল ও বিশ্ববিদ্যালয় পণ্য; সম্প্রসারিত এআই ফিচার বাস্তবায়নাধীন।'],kpi:['Admission conversion · service turnaround · data completeness','ভর্তির রূপান্তর · সেবার সময় · তথ্যের পূর্ণতা']},
{id:'leadershipos',name:'LeadershipOS',category:['Decisions & accountability','সিদ্ধান্ত ও জবাবদিহিতা'],icon:'network',tint:'#eeedf6',color:'#7c6995',stage:['Capability roadmap','সক্ষমতার রোডম্যাপ'],summary:['Turn decisions into accountable action. Connect roles, commitments, evidence and outcomes in one leadership view.','সিদ্ধান্ত থেকে জবাবদিহিমূলক কাজ। ভূমিকা, প্রতিশ্রুতি, প্রমাণ ও ফলাফল এক জায়গায়।'],description:['A governed leadership operating model for institutions and enterprises. Written decisions, delegated work and evidence-backed KPIs connect to Central MIS, Central Dashboard and CEPAO through defined authority boundaries.','প্রতিষ্ঠান ও ব্যবসার জন্য নিয়ন্ত্রিত নেতৃত্ব ব্যবস্থা। লিখিত সিদ্ধান্ত, অর্পিত কাজ ও প্রমাণভিত্তিক কেপিআই নির্ধারিত কর্তৃত্ব অনুযায়ী Central MIS, Central Dashboard ও CEPAO-তে যুক্ত হয়।'],audiences:['Industry','Government','Academia'],features:[['Position Factory','পদের কাঠামো','Define roles, jurisdiction, targets, job descriptions and delegation.','ভূমিকা, অধিক্ষেত্র, লক্ষ্য, কাজের বিবরণ ও দায়িত্ব অর্পণ।'],['Meeting to execution','সভা থেকে বাস্তবায়ন','Convert meeting decisions into owned actions, deadlines and evidence.','সভার সিদ্ধান্তকে দায়িত্ব, সময়সীমা ও প্রমাণসহ কাজে রূপান্তর করুন।'],['Central intelligence','কেন্দ্রীয় তথ্য','Connect authorized management views to Central MIS and CEPAO.','অনুমোদিত ব্যবস্থাপনা দৃশ্য Central MIS ও CEPAO-এর সাথে যুক্ত করুন।'],['Governed agents','নিয়ন্ত্রিত এজেন্ট','AI proposes and drafts; responsible people retain reserved decisions.','এআই প্রস্তাব ও খসড়া তৈরি করে; গুরুত্বপূর্ণ সিদ্ধান্ত দায়িত্বপ্রাপ্ত মানুষের হাতে।']],source:'',readiness:['Blueprint and controlled demonstration stage. Production rollout, integrations and role-specific evidence remain deployment gates.','ব্লুপ্রিন্ট ও নিয়ন্ত্রিত প্রদর্শনের পর্যায়। প্রোডাকশন ও সংযোগের আগে যাচাই প্রয়োজন।'],kpi:['On-time actions · evidence coverage · overdue commitments','সময়ে সম্পন্ন কাজ · প্রমাণের পরিসর · বিলম্বিত প্রতিশ্রুতি']}
];
export const pipeline=[
['DUDOS','Capability roadmap','Governed discovery, customer lifecycle, offers and enterprise agentic execution.','নিয়ন্ত্রিত গ্রাহক অনুসন্ধান, জীবনচক্র, অফার ও এজেন্টিক বাস্তবায়ন।'],
['DAIOS / EADC','Capability roadmap','Shared architecture, standards, evidence and enterprise AI controls.','সমন্বিত স্থাপত্য, মানদণ্ড, প্রমাণ ও এন্টারপ্রাইজ এআই নিয়ন্ত্রণ।'],
['RegistrarOS','Capability roadmap','Institutional services, policy tracking and accountable registrar operations.','প্রাতিষ্ঠানিক সেবা, নীতিমালা ও রেজিস্ট্রার কার্যক্রমে জবাবদিহিতা।'],
['CareerOS / Skill.jobs','Product + roadmap','Skills, verified employability, recruitment and career pathways.','দক্ষতা, যাচাইকৃত কর্মসংস্থান সক্ষমতা, নিয়োগ ও ক্যারিয়ার।'],
['Student360','Capability roadmap','A connected student lifecycle, services, development and outcomes.','শিক্ষার্থীর জীবনচক্র, সেবা, উন্নয়ন ও ফলাফল।'],
['SHOS','Capability roadmap','Hospitality operations, online ordering and service intelligence.','আতিথেয়তা কার্যক্রম, অনলাইন অর্ডার ও সেবা বিশ্লেষণ।'],
['MyeKids','Capability roadmap','Creative learning, family participation and responsible innovation.','সৃজনশীল শিক্ষা, পরিবারের অংশগ্রহণ ও দায়িত্বশীল উদ্ভাবন।'],
['Central AI','Product scope to verify','Conversational lead capture, customer service and CRM connectivity.','আলাপভিত্তিক লিড সংগ্রহ, গ্রাহক সেবা ও সিআরএম সংযোগ।'],
['AICA / NISA','Concept prototype','Citizen and institutional service concepts for consultative co-design.','নাগরিক ও প্রাতিষ্ঠানিক সেবা নিয়ে যৌথ নকশার ধারণা।'],
['AI Cloud, IoT & robotics','Capability roadmap','Explore governed compute, edge intelligence and physical automation pilots.','নিয়ন্ত্রিত কম্পিউটিং, এজ ইন্টেলিজেন্স ও বাস্তব অটোমেশন পাইলট।'],
['SolarAchieve','Capability roadmap','Energy and IoT innovation with separately verified deployment scope.','যাচাইকৃত বাস্তবায়ন অনুযায়ী জ্বালানি ও আইওটি উদ্ভাবন।']
];
export const services=[
{title:['AI strategy & consultancy','এআই কৌশল ও পরামর্শ'],text:['Find the right starting point. Assess workflows, data and business value, then define a pilot with measurable success.','সঠিক সূচনা বেছে নিন। কাজ, তথ্য ও ব্যবসায়িক মূল্য মূল্যায়ন করে পরিমাপযোগ্য পাইলট নির্ধারণ করুন।'],icon:'compass',deliver:['Readiness assessment','Use-case shortlist','Pilot success criteria']},
{title:['Solutions & integration','সমাধান ও সংযোগ'],text:['Connect AI to the systems you already use. Scope custom applications, Odoo workflows, APIs and governed agents.','বিদ্যমান ব্যবস্থার সাথে এআই যুক্ত করুন। কাস্টম অ্যাপ, Odoo কাজ, API ও নিয়ন্ত্রিত এজেন্টের পরিসর নির্ধারণ করুন।'],icon:'workflow',deliver:['Solution design','API and data mapping','Reviewed workflow automation']},
{title:['Training & managed support','প্রশিক্ষণ ও সহায়তা'],text:['Build confidence beyond launch. Enable your people through training, adoption support and an agreed service plan.','চালুর পরেও সক্ষমতা বাড়ান। প্রশিক্ষণ, গ্রহণযোগ্যতা ও নির্ধারিত সেবা পরিকল্পনায় মানুষকে প্রস্তুত করুন।'],icon:'headset',deliver:['Team workshops','Onboarding plan','Support and review schedule']},
{title:['AI infrastructure advisory','এআই অবকাঠামোর পরামর্শ'],text:['Plan compute, connectivity, model access and security for cloud, private or hybrid workloads. Capacity and service levels are confirmed in the proposal.','ক্লাউড, প্রাইভেট বা হাইব্রিড কাজের জন্য কম্পিউটিং, সংযোগ ও নিরাপত্তা পরিকল্পনা করুন।'],icon:'server',deliver:['Workload sizing','Hosting options','Cost and resilience plan']},
{title:['Research & co-innovation','গবেষণা ও যৌথ উদ্ভাবন'],text:['Bring industry problems into academic collaboration. Define a research question, evidence, IP terms and a route to a controlled pilot.','শিল্পখাতের সমস্যা একাডেমিক সহযোগিতায় আনুন। গবেষণা প্রশ্ন, প্রমাণ, মেধাস্বত্ব ও পাইলট নির্ধারণ করুন।'],icon:'flask',deliver:['Research brief','Industry mentor','Pilot and commercialization path']},
{title:['AI marketing & growth','এআই বিপণন ও প্রবৃদ্ধি'],text:['Connect content, search, social campaigns and consented enquiries to a measurable sales pipeline.','কনটেন্ট, সার্চ, সামাজিক প্রচার ও সম্মতিভিত্তিক অনুসন্ধানকে পরিমাপযোগ্য বিক্রয় সুযোগে যুক্ত করুন।'],icon:'megaphone',deliver:['Channel and content plan','CRM attribution','Campaign performance review']}
];
export const audiences=[
{label:['Students','শিক্ষার্থী'],title:['Your ideas deserve a real-world future.','আপনার ধারণা বাস্তবে অবদান রাখুক।'],text:['Join a path from learning to building. Bring your curiosity to practical projects with mentors, evidence of your work and opportunities to connect with industry.','শেখা থেকে নির্মাণের পথে আসুন। মেন্টর, কাজের প্রমাণ ও শিল্পখাতের সাথে সংযোগের সুযোগে বাস্তব প্রকল্প তৈরি করুন।'],items:[['Apply to the AI Product Hub','এআই প্রোডাক্ট হাবে আবেদন'],['Explore internships and research projects','ইন্টার্নশিপ ও গবেষণার সুযোগ'],['Build a portfolio of verified work','যাচাইকৃত কাজের পোর্টফোলিও তৈরি']],cta:['Explore student opportunities','শিক্ষার্থীর সুযোগ দেখুন'],icon:'graduation',intent:'Student application'},
{label:['Academia','শিক্ষা ও গবেষণা'],title:['Connect the classroom to what comes next.','শ্রেণিকক্ষকে ভবিষ্যতের সাথে যুক্ত করুন।'],text:['Bring teaching, institutional operations and applied research into a shared conversation. Explore AI Professor, Eduvas and collaborations with the AI Product Hub.','শিক্ষাদান, প্রাতিষ্ঠানিক পরিচালনা ও প্রয়োগমূলক গবেষণাকে একসাথে আনুন। AI Professor, Eduvas ও এআই প্রোডাক্ট হাব দেখুন।'],items:[['AI-assisted teaching with human oversight','মানুষের তত্ত্বাবধানে এআই সহায়ক শিক্ষাদান'],['Integrated academic and campus operations','সমন্বিত একাডেমিক ও ক্যাম্পাস পরিচালনা'],['Research partnerships and living labs','গবেষণার অংশীদারিত্ব ও লিভিং ল্যাব']],cta:['Discuss an institutional pilot','প্রাতিষ্ঠানিক পাইলট নিয়ে আলোচনা'],icon:'building',intent:'Institutional pilot'},
{label:['Industry','শিল্প ও ব্যবসা'],title:['Make intelligence part of everyday work.','দৈনন্দিন কাজে বুদ্ধিমত্তা যুক্ত করুন।'],text:['Start with a business problem. Connect HR, leadership, customer engagement and your existing systems through a phased, measurable adoption plan.','ব্যবসায়িক সমস্যা দিয়ে শুরু করুন। এইচআর, নেতৃত্ব, গ্রাহক যোগাযোগ ও বিদ্যমান ব্যবস্থা পরিমাপযোগ্য পরিকল্পনায় যুক্ত করুন।'],items:[['Discover Perfect HR and LeadershipOS','Perfect HR ও LeadershipOS দেখুন'],['Integrate with your existing software','বিদ্যমান সফটওয়্যারের সাথে সংযোগ'],['Measure time, quality and commercial value','সময়, মান ও বাণিজ্যিক মূল্য মাপুন']],cta:['Find your solution','আপনার সমাধান খুঁজুন'],icon:'briefcase',intent:'Business enquiry'},
{label:['Government','সরকার'],title:['Co-design services around public value.','জনকল্যাণকে কেন্দ্র করে সেবা তৈরি করুন।'],text:['Explore Bangla-first service concepts, institutional accountability and evidence-based decision support through a clearly scoped, human-supervised pilot.','বাংলাভিত্তিক সেবা, প্রাতিষ্ঠানিক জবাবদিহিতা ও প্রমাণভিত্তিক সিদ্ধান্ত মানুষের তত্ত্বাবধানে পাইলট হিসেবে অন্বেষণ করুন।'],items:[['Consultative discovery and service mapping','পরামর্শভিত্তিক অনুসন্ধান ও সেবার ম্যাপিং'],['Institutional KPI and accountability concepts','প্রাতিষ্ঠানিক কেপিআই ও জবাবদিহিতার ধারণা'],['Clear authority, privacy and acceptance gates','কর্তৃত্ব, গোপনীয়তা ও গ্রহণযোগ্যতার যাচাই']],cta:['Start a public-sector conversation','সরকারি খাতের আলোচনা শুরু করুন'],icon:'landmark',intent:'Government consultation'}
];
export const insights=[
{id:'accountable-ai',category:['Perspective','দৃষ্টিভঙ্গি'],title:['From an AI answer to accountable action','এআই উত্তর থেকে জবাবদিহিমূলক কাজ'],summary:['Why a source, an owner and a next step belong in every enterprise AI workflow.','কেন প্রতিটি এআই কার্যক্রমে উৎস, দায়িত্বপ্রাপ্ত ব্যক্তি ও পরবর্তী পদক্ষেপ প্রয়োজন।'],body:[['Start with a question that matters','গুরুত্বপূর্ণ প্রশ্ন দিয়ে শুরু','A useful AI workflow begins with a defined operational problem. Identify the decision, the allowed information and the person responsible for reviewing the result.','কার্যকর এআই কাজ শুরু হয় একটি নির্দিষ্ট সমস্যা দিয়ে। সিদ্ধান্ত, অনুমোদিত তথ্য ও পর্যালোচনার দায়িত্বপ্রাপ্ত ব্যক্তিকে নির্ধারণ করুন।'],['Make the evidence visible','প্রমাণ দৃশ্যমান করুন','Record the source, its date and any missing information. A confident-sounding response is not evidence. Separate observations from proposed actions.','উৎস, তারিখ ও অনুপস্থিত তথ্য লিখুন। আত্মবিশ্বাসী উত্তর প্রমাণ নয়। পর্যবেক্ষণ ও প্রস্তাবিত কাজ আলাদা রাখুন।'],['Close the loop','কাজের চক্র সম্পন্ন করুন','Assign the approved action to an owner with a deadline. Record completion evidence and review whether the intended outcome occurred. LeadershipOS is designed around this principle.','অনুমোদিত কাজ দায়িত্ব ও সময়সীমাসহ অর্পণ করুন। সমাপ্তির প্রমাণ লিখুন এবং লক্ষ্য অর্জিত হয়েছে কি না পর্যালোচনা করুন।']]},
{id:'learning-to-building',category:['Innovation','উদ্ভাবন'],title:['A pathway from learning to building','শেখা থেকে নির্মাণের পথ'],summary:['The AI Product Hub vision connects students, mentors and real industry problems.','এআই প্রোডাক্ট হাব শিক্ষার্থী, মেন্টর ও বাস্তব শিল্প সমস্যাকে যুক্ত করে।'],body:[['A practical production model','বাস্তব উৎপাদন মডেল','The proposed AI Product Hub brings multidisciplinary students into small product teams. Work should leave an evidence trail: the problem brief, a working artifact, feedback and a documented improvement.','প্রস্তাবিত এআই প্রোডাক্ট হাবে বিভিন্ন বিষয়ের শিক্ষার্থীরা ছোট পণ্য দলে কাজ করবে। সমস্যা, কাজের ফল, মতামত ও উন্নয়নের প্রমাণ থাকবে।'],['Mentorship and academic value','মেন্টর ও একাডেমিক মূল্য','Students need technical review and subject expertise alongside the tools. Internship, credit and award decisions remain subject to the institution’s approved rules and documented assessment.','শিক্ষার্থীদের প্রযুক্তিগত পর্যালোচনা ও বিষয়ভিত্তিক দক্ষতা দরকার। ইন্টার্নশিপ, ক্রেডিট ও পুরস্কার প্রাতিষ্ঠানিক নীতিমালা অনুযায়ী হবে।'],['A route toward impact','প্রভাবের পথে','Industry partners can provide problems, mentors and pilot settings. Track validated prototypes, accepted pilots and learner outcomes separately from proposed commercial opportunities.','শিল্প অংশীদাররা সমস্যা, মেন্টর ও পাইলট দিতে পারে। যাচাইকৃত প্রোটোটাইপ, গৃহীত পাইলট ও শিক্ষার্থীর ফলাফল পৃথকভাবে মাপুন।']]},
{id:'pilot-before-scale',category:['Practical guide','ব্যবহারিক নির্দেশনা'],title:['What a useful first AI pilot should prove','প্রথম এআই পাইলট কী প্রমাণ করবে'],summary:['Define the workflow, baseline and acceptance evidence before you scale.','প্রসারের আগে কাজ, প্রাথমিক অবস্থা ও গ্রহণযোগ্যতার প্রমাণ নির্ধারণ করুন।'],body:[['Choose one bounded workflow','একটি নির্দিষ্ট কাজ বাছুন','Begin with a process where the current time, quality and cost can be measured. Avoid combining unrelated problems into a single pilot.','এমন কাজ বাছুন যার সময়, মান ও ব্যয় মাপা যায়। একটি পাইলটে অসংশ্লিষ্ট সমস্যা মেশাবেন না।'],['Write success criteria','সাফল্যের মানদণ্ড লিখুন','Agree the users, data boundary, review responsibility and required evidence. Choose targets after measuring the baseline, rather than promising a percentage saving in advance.','ব্যবহারকারী, তথ্যের সীমা, পর্যালোচনার দায়িত্ব ও প্রমাণ নির্ধারণ করুন। প্রাথমিক পরিমাপের পর লক্ষ্য ঠিক করুন।'],['Review the outcome','ফলাফল পর্যালোচনা','Use the results to decide whether to improve, stop or scale. Keep integration costs, support, security review and user feedback visible in that decision.','ফলাফল দিয়ে উন্নয়ন, বন্ধ বা প্রসারের সিদ্ধান্ত নিন। সংযোগের ব্যয়, সহায়তা, নিরাপত্তা ও মতামত বিবেচনায় রাখুন।']]}
];
export const routeTitles:Record<string,string>={'/':'AI solutions, built on a legacy of possibility','/solutions':'Explore our AI portfolio','/services':'Turn AI ambition into a practical plan','/ecosystem':'A future everyone can help build','/insights':'Ideas that move the conversation forward','/expo':'Every conversation can become an opportunity','/contact':'Let’s build what comes next','/about':'A legacy of building what comes next','/trust':'Trust is part of the solution','/login':'Your Daffodil AI workspace','/developers':'Connect your systems with confidence','/privacy':'Privacy & data choices','/terms':'Website & enquiry terms'};
