export type FieldSpec={key:string;label:string;bn:string;type?:string;options?:string[];required?:boolean};
export type ResourceSpec={name:string;bn:string;singular:string;description:string;fields:FieldSpec[]};
const field=(key:string,label:string,bn:string,type='text',options?:string[],required=false):FieldSpec=>({key,label,bn,type,options,required});
export const stages=['New','Contacted','Qualified','Demo scheduled','Proposal','Won','Lost'];
export const registry:Record<string,ResourceSpec>={
 opportunities:{name:'Opportunities',bn:'ব্যবসায়িক সুযোগ',singular:'Opportunity',description:'Track an agreed commercial next step, not a forecast presented as revenue.',fields:[field('title','Opportunity title','সুযোগের নাম','text',undefined,true),field('organization','Organization','প্রতিষ্ঠান','text',undefined,true),field('leadRef','Enquiry reference','অনুসন্ধানের রেফারেন্স'),field('product','Product / service','পণ্য / সেবা'),field('value','Estimated value','সম্ভাব্য মূল্য','number'),field('currency','Currency','মুদ্রা','select',['BDT','USD','EUR','GBP']),field('stage','Stage','ধাপ','select',['Discovery','Qualified','Demo','Proposal','Negotiation','Won','Lost']),field('owner','Accountable owner','দায়িত্বপ্রাপ্ত ব্যক্তি'),field('due','Next-action date','পরবর্তী কাজের তারিখ','date'),field('nextAction','Next action','পরবর্তী কাজ'),field('acceptance','Pilot / acceptance criteria','পাইলট / গ্রহণযোগ্যতার শর্ত','textarea'),field('notes','Notes & evidence','নোট ও প্রমাণ','textarea')]},
 meetings:{name:'Meetings & demos',bn:'সভা ও ডেমো',singular:'Meeting',description:'Record who met, what was agreed and who owns the next action.',fields:[field('title','Meeting / demo title','সভার নাম','text',undefined,true),field('organization','Organization','প্রতিষ্ঠান'),field('contact','Contact / lead reference','যোগাযোগ / লিড'),field('type','Type','ধরন','select',['Demo','Discovery','Government consultation','Research','Partner','Internal']),field('scheduled','Date & time','তারিখ ও সময়','datetime-local'),field('timezone','Timezone','টাইমজোন','select',['Asia/Dhaka','UTC']),field('owner','Host / owner','আয়োজক / দায়িত্ব'),field('participants','Participants','অংশগ্রহণকারী'),field('product','Product','পণ্য'),field('status','Status','অবস্থা','select',['Requested','Confirmed','Completed','Cancelled']),field('requirements','Requirements','প্রয়োজন','textarea'),field('decisions','Decisions & next steps','সিদ্ধান্ত ও পরবর্তী কাজ','textarea'),field('due','Follow-up date','ফলোআপের তারিখ','date'),field('evidence','Evidence URL','প্রমাণের URL','url')]},
 exhibitors:{name:'Exhibitors & partners',bn:'প্রদর্শক ও অংশীদার',singular:'Exhibitor',description:'Keep verified exhibitor sources and permission-based outreach in one register.',fields:[field('title','Organization name','প্রতিষ্ঠানের নাম','text',undefined,true),field('event','Event name','ইভেন্ট'),field('booth','Booth / stand','স্টল'),field('sector','Sector','খাত'),field('contact','Contact person','যোগাযোগের ব্যক্তি'),field('designation','Designation','পদবি'),field('email','Email','ইমেইল','email'),field('phone','Phone','ফোন'),field('website','Website','ওয়েবসাইট','url'),field('source','Directory / source URL','তালিকা / উৎস','url'),field('interest','Partnership interest','সহযোগিতার আগ্রহ','textarea'),field('owner','Outreach owner','যোগাযোগের দায়িত্ব'),field('status','Status','অবস্থা','select',['To research','Verified','Permission obtained','Met','Follow-up','Closed']),field('consent','Contact permission evidence','যোগাযোগের সম্মতির প্রমাণ'),field('due','Next visit / action','পরবর্তী কাজ','date')]},
 staff:{name:'Expo staff & duties',bn:'এক্সপোর স্টাফ ও দায়িত্ব',singular:'Staff assignment',description:'Record actual staff identity, shift, product readiness, attendance and responsibility.',fields:[field('title','Full name','পূর্ণ নাম','text',undefined,true),field('designation','Designation','পদবি'),field('unit','Business unit','ইউনিট'),field('staffId','Staff identification','স্টাফ পরিচিতি'),field('email','Work email','কর্মস্থলের ইমেইল','email'),field('phone','Work phone','কর্মস্থলের ফোন'),field('event','Event','ইভেন্ট'),field('shift','Shift / availability','শিফট / সময়'),field('product','Product expertise','পণ্য দক্ষতা'),field('duty','Assigned duty','নির্ধারিত দায়িত্ব'),field('backup','Backup person','বিকল্প ব্যক্তি'),field('passStatus','Pass status','পাসের অবস্থা','select',['Not requested','Requested','Confirmed','Not required']),field('readiness','Demo readiness','ডেমোর প্রস্তুতি','select',['Needs training','Rehearsal pending','Verified','Unavailable']),field('photoUrl','Approved staff photo URL','অনুমোদিত স্টাফ ছবির URL','url'),field('permission','Profile/photo approval reference','প্রোফাইল / ছবির অনুমোদন'),field('status','Duty status','দায়িত্বের অবস্থা','select',['Scheduled','On duty','Completed','Absent'])]},
 students:{name:'Student applications',bn:'শিক্ষার্থীর আবেদন',singular:'Student review',description:'Track selection, mentorship and evidence; credit and awards require academic authority.',fields:[field('title','Student name','শিক্ষার্থীর নাম','text',undefined,true),field('leadRef','Enquiry reference','অনুসন্ধানের রেফারেন্স'),field('institution','Institution','প্রতিষ্ঠান'),field('programme','Programme / semester','বিষয় / সেমিস্টার'),field('email','Email','ইমেইল','email'),field('skills','Skills & interests','দক্ষতা ও আগ্রহ','textarea'),field('portfolio','Portfolio / repository URL','পোর্টফোলিও / রিপোজিটরি','url'),field('availability','Weekly availability','সাপ্তাহিক সময়'),field('track','Preferred track','পছন্দের ক্ষেত্র','select',['AI engineering','Product design','Research','Robotics / IoT','Sales & marketing','Content & community']),field('status','Review stage','পর্যালোচনার ধাপ','select',['Applied','Screening','Interview','Selected','Waitlisted','Not selected','Onboarded','Completed']),field('mentor','Mentor / supervisor','মেন্টর / সুপারভাইজার'),field('nda','NDA status','NDA অবস্থা','select',['Not started','Pending','Signed']),field('project','Assigned project','নির্ধারিত প্রকল্প'),field('credit','Credit / award review','ক্রেডিট / পুরস্কার পর্যালোচনা'),field('due','Next review date','পরবর্তী পর্যালোচনা','date'),field('evidence','Completion evidence URL','সমাপ্তির প্রমাণ','url')]},
 research:{name:'Research & discussions',bn:'গবেষণা ও আলোচনা',singular:'Research record',description:'Retain discussions, sources, findings, limitations and commercialization opportunities.',fields:[field('title','Research / discussion title','গবেষণা / আলোচনার শিরোনাম','text',undefined,true),field('topic','Topic','বিষয়','select',['Bangla AI','Education','Enterprise AI','Government services','AI agents','AI infrastructure','IoT / robotics','Responsible AI','Marketing automation']),field('source','Source URL','উৎসের URL','url'),field('sourceDate','Source date','উৎসের তারিখ','date'),field('owner','Research owner','গবেষণার দায়িত্ব'),field('institution','Institution / partner','প্রতিষ্ঠান / অংশীদার'),field('problem','Problem / research question','সমস্যা / গবেষণার প্রশ্ন','textarea'),field('findings','Findings / discussion notes','ফলাফল / আলোচনার নোট','textarea'),field('limitations','Limitations & unanswered questions','সীমা ও অনুত্তরিত প্রশ্ন','textarea'),field('product','Related product','সংশ্লিষ্ট পণ্য'),field('ip','IP / publication permission','মেধাস্বত্ব / প্রকাশের অনুমতি'),field('nextAction','Next action','পরবর্তী কাজ'),field('due','Review date','পর্যালোচনার তারিখ','date'),field('status','Status','অবস্থা','select',['Draft','Researching','Review','Verified','Archived'])]},
 content:{name:'Content & SEO',bn:'কনটেন্ট ও এসইও',singular:'Content item',description:'Draft and review multilingual product stories, articles, videos and campaigns before publication.',fields:[field('title','Content title','কনটেন্টের শিরোনাম','text',undefined,true),field('type','Format','ধরন','select',['Article','Product page','Case study','Social post','Video script','Webinar','Press note','Brochure']),field('locale','Language','ভাষা','select',['English','Bangla']),field('audience','Audience','লক্ষ্যগোষ্ঠী'),field('product','Related product','সংশ্লিষ্ট পণ্য'),field('slug','Page slug','পেজ স্লাগ'),field('keyword','Search intent / primary topic','সার্চের উদ্দেশ্য / বিষয়'),field('metaTitle','SEO title','এসইও টাইটেল'),field('description','Meta / social description','মেটা / সোশ্যাল বিবরণ','textarea'),field('body','Draft content','খসড়া কনটেন্ট','textarea'),field('source','Claim / evidence URL','দাবি / প্রমাণের URL','url'),field('author','Author','লেখক'),field('reviewer','Reviewer','পর্যালোচক'),field('status','Editorial stage','সম্পাদনার ধাপ','select',['Draft','Review','Approved','Scheduled','Published externally','Archived']),field('due','Planned publication date','প্রকাশের সম্ভাব্য তারিখ','date'),field('publishedUrl','Verified published URL','যাচাইকৃত প্রকাশিত URL','url'),field('translationOf','Linked translation ID','অনুবাদের মূল আইডি')]},
 campaigns:{name:'Campaigns & social',bn:'ক্যাম্পেইন ও সামাজিক মাধ্যম',singular:'Campaign',description:'Connect channel activity to consented enquiries, opportunities and verified outcomes.',fields:[field('title','Campaign name','ক্যাম্পেইনের নাম','text',undefined,true),field('channel','Channel','মাধ্যম','select',['LinkedIn','Facebook','Instagram','YouTube','X','TikTok','WhatsApp','Email','SEO / Search','Webinar','Partner referral','Expo']),field('goal','Objective','লক্ষ্য','select',['Awareness','Qualified enquiries','Demo bookings','Student applications','Partner leads','Adoption','Retention']),field('audience','Audience / market','লক্ষ্যগোষ্ঠী / বাজার'),field('owner','Campaign owner','ক্যাম্পেইনের দায়িত্ব'),field('source','UTM source','UTM source'),field('medium','UTM medium','UTM medium'),field('campaign','UTM campaign slug','UTM campaign'),field('landing','Landing URL','ল্যান্ডিং URL','url'),field('budget','Approved budget','অনুমোদিত বাজেট','number'),field('currency','Currency','মুদ্রা','select',['BDT','USD']),field('start','Start date','শুরুর তারিখ','date'),field('due','End / review date','শেষ / পর্যালোচনার তারিখ','date'),field('target','Target / KPI','লক্ষ্য / কেপিআই'),field('actual','Verified outcome','যাচাইকৃত ফলাফল'),field('evidence','Analytics evidence URL','অ্যানালিটিক্সের প্রমাণ','url'),field('approval','Content / spend approval','কনটেন্ট / ব্যয়ের অনুমোদন'),field('status','Status','অবস্থা','select',['Draft','Review','Approved','Scheduled','Active externally','Completed','Paused'])]},
 tasks:{name:'Actions & accountability',bn:'কাজ ও জবাবদিহিতা',singular:'Action',description:'Every commitment has one owner, a deadline and a completion record.',fields:[field('title','Action title','কাজের নাম','text',undefined,true),field('owner','Accountable owner','দায়িত্বপ্রাপ্ত ব্যক্তি','text',undefined,true),field('due','Due date','সময়সীমা','date',undefined,true),field('priority','Priority','অগ্রাধিকার','select',['High','Medium','Low']),field('related','Related lead / project / meeting','সংশ্লিষ্ট লিড / প্রকল্প / সভা'),field('outcome','Expected outcome / KPI','কাঙ্ক্ষিত ফলাফল / কেপিআই','textarea'),field('status','Status','অবস্থা','select',['Open','In progress','Blocked','For review','Completed']),field('blocker','Blocker / support needed','বাধা / সহায়তার প্রয়োজন','textarea'),field('evidence','Completion evidence URL','সমাপ্তির প্রমাণ','url')]},
 tickets:{name:'Support & privacy',bn:'সহায়তা ও গোপনীয়তা',singular:'Support case',description:'Route service issues, corrections, opt-outs and privacy requests to a responsible person.',fields:[field('title','Case title','বিষয়ের নাম','text',undefined,true),field('leadRef','Request reference','অনুরোধের রেফারেন্স'),field('contact','Contact','যোগাযোগ'),field('email','Email','ইমেইল','email'),field('type','Type','ধরন','select',['Product support','Demo help','Billing question','Data access','Correction','Deletion request','Marketing opt-out','Complaint']),field('product','Product','পণ্য'),field('priority','Priority','অগ্রাধিকার','select',['Urgent','High','Normal','Low']),field('description','Description','বিবরণ','textarea'),field('owner','Assigned owner','নির্ধারিত দায়িত্ব'),field('due','Target response date','উত্তরের লক্ষ্য তারিখ','date'),field('status','Status','অবস্থা','select',['New','Triaged','In progress','Waiting for requester','Resolved','Closed']),field('resolution','Resolution / review evidence','সমাধান / প্রমাণ','textarea')]},
 automation:{name:'Automation register',bn:'অটোমেশন রেজিস্টার',singular:'Automation',description:'Record triggers, sources, tool permissions and human controls before activation.',fields:[field('title','Automation name','অটোমেশনের নাম','text',undefined,true),field('trigger','Trigger','ট্রিগার'),field('input','Input sources','ইনপুট উৎস'),field('action','Proposed action','প্রস্তাবিত কাজ','textarea'),field('tools','API / MCP tools','API / MCP টুল'),field('tenantScope','Allowed tenant / data scope','অনুমোদিত প্রতিষ্ঠান / তথ্য'),field('owner','Accountable owner','দায়িত্বপ্রাপ্ত ব্যক্তি'),field('approval','Required human approval','মানুষের অনুমোদন'),field('limits','Cost / frequency / action limits','ব্যয় / পুনরাবৃত্তি / কাজের সীমা'),field('fallback','Failure / rollback / kill switch','ব্যর্থতা / প্রত্যাবর্তন / বন্ধের ব্যবস্থা','textarea'),field('evidence','Test / evaluation evidence URL','পরীক্ষার প্রমাণ','url'),field('status','Status','অবস্থা','select',['Proposed','Design','Sandbox','Review','Approved for external implementation','Paused'])]}
};
export const connectors=[
{name:'Odoo CRM',purpose:'Consented lead and opportunity handoff',kind:'crm',state:'Adapter available · not configured',fields:'ODOO_URL, ODOO_DB, ODOO_UID, ODOO_API_KEY; optional ODOO_COMPANY_ID'},
{name:'AI model / RAG gateway',purpose:'Approved-source conversational assistance',kind:'ai',state:'Integration specification',fields:'Provider, model, tenant-scoped retrieval, evaluation, budgets and human escalation'},
{name:'Business-card OCR',purpose:'Extract text, then review fields with the visitor',kind:'ocr',state:'Gateway adapter · not configured',fields:'OCR_GATEWAY_URL, OCR_GATEWAY_TOKEN; data-processing agreement'},
{name:'MCP',purpose:'Read-only product catalogue tools',kind:'mcp',state:'Read-only endpoint implemented',fields:'/api/mcp; no CRM or private data exposed'},
{name:'WhatsApp / email',purpose:'Consented responses, reminders and invitations',kind:'messaging',state:'Not configured',fields:'Verified business accounts, templates, opt-out and send authority'},
{name:'GA4 / Search Console',purpose:'Search visibility, traffic and conversion attribution',kind:'analytics',state:'Not configured',fields:'Properties, consent mode, events and validation'},
{name:'Meta / LinkedIn / YouTube / X / TikTok',purpose:'Campaign publication and evidence-backed reporting',kind:'social',state:'Not configured',fields:'Approved accounts, platform permissions, content approval and spend limits'},
{name:'Perfect HR / LeadershipOS / Central MIS',purpose:'Identity, people, accountability and authorized oversight',kind:'ecosystem',state:'Integration specification',fields:'Source-of-truth mapping; role and jurisdiction contracts'},
{name:'LMS / GitHub',purpose:'Student learning, projects and repository evidence',kind:'learning',state:'Integration specification',fields:'Institution-specific APIs; scoped accounts; NDA and academic review'}
];
export const sources=[
{title:'MPT-WEB-001 · Website UI/UX v1.1.0',url:'https://docs.google.com/document/d/1BRHB4Po5O4KOm_O-gRIIpwYOJWG_IEvpHF2gMsCB6S8/edit',use:'Public / authenticated / operational layers; dynamic forms, accessibility, SEO, integrations and release controls.'},
{title:'Universal Multi-Layer Login, Control and Security Standard',url:'https://docs.google.com/document/d/1mAUDkEEmML3a8VcR07XkGgHnERDH8gmlJnJJFDkQIoE/edit',use:'Jurisdiction, membership, reserved authority, source-of-truth and audit requirements.'},
{title:'MPT-GRW-001 · Brand, Marketing, Social, GTM & Growth v1.1.0',url:'https://docs.google.com/document/d/1CcwgW9JS3UgkxK6B-a6CS1-Jcg-jZMrY/edit',use:'Consented channel acquisition, CRM attribution, truthful claims and human publishing control.'},
{title:'MPT-SEO-001 · Content & SEO v1.0.0',url:'https://docs.google.com/document/d/14eAh01RRud-ouygtBrkRyaFVdem27rtuxYnH2T8jztc/edit',use:'Metadata, language URLs, indexable public content, editorial sources and private-route exclusion.'},
{title:'Daffodil AI Summit Blueprint v1.0',url:'https://docs.google.com/document/d/1FyuB6dbLd5K9bxZK_M4OBNX-0hjjf1g3IG9VG8yKmK0/edit',use:'Permanent AI sales platform, portfolio, consultancy and enquiry ownership.'},
{title:'Innovation Fair Pavilion Execution Guideline v1.0',url:'https://docs.google.com/document/d/1M5qHhfu6fBqE5ZTjyEbanBJ8AE3t4M0ptC5Lgpo_A6g/edit',use:'Maturity labels, consented lead capture, 24/48-hour follow-up targets and evidence.'},
{title:'Perfect HR Global Dynamic Website Master Prompt',url:'https://docs.google.com/document/d/1eOoKFCd8K1cVAljurHIuDxFzfZvrngOsBi-4zznsCF4/edit',use:'Existing HR scope versus AI roadmap, modular pricing and enterprise integrations.'},
{title:'LeadershipOS Website Build Prompt v2.1',url:'https://docs.google.com/document/d/19ft1F3u6UfYauLouTWDF_P3pqMyY_xcBAc3EUSb4OO0/edit',use:'Central MIS / CEPAO boundaries, evidence-driven leadership and governed agents.'},
{title:'AI Professor Reference Architecture P29-09',url:'https://docs.google.com/document/d/1eqGQzxY7G1qkw4zltx07Js2vKBvV_CpEcw9C0RZV4oQ/edit',use:'14-component roadmap pending ratification; academic human authority.'},
{title:'AI Product Hub Global Technology Partnership Proposal',url:'https://docs.google.com/document/d/1sGGLu1Jzy34CtgWopGTfoXOMD01kwEh9bSQPJBzSV4c/edit',use:'Proposed 25-student / 120-day pilot, mentors, credit review and commercialization.'}
];
export const coverage=[
['Public portfolio','Implemented','Four priority products; detail routes, comparison, sectors and pipeline stages.'],
['Service selling','Implemented','Consultancy, integration, training, infrastructure, research and growth enquiry journeys.'],
['Bilingual experience','Implemented foundation','English/Bangla public copy and labels; administrative enumerations retain canonical English values.'],
['Expo CRM','Implemented','Persistent leads, consent, card/photo attachment, staff owner, follow-up date and lead stages.'],
['Tenancy & access','Implemented foundation','Server-enforced tenant membership and role permissions; administrative setup uses an explicit email allowlist.'],
['Self-service','Implemented','Authenticated users can view their own submitted requests; sign-in alone gives no team access.'],
['Operations registers','Implemented','Opportunities, meetings, exhibitors, staff, students, research, content, campaigns, tasks, support and automation.'],
['Odoo CRM','Configuration required','Manual authorized push adapter with idempotent reference reconciliation. No live external connection tested.'],
['Card recognition','Configuration required','Image capture/upload and editable contact review work; OCR gateway credentials required.'],
['AI assistance','Limited foundation','Catalogue finder and rule-based guidance available. Live model/RAG generation requires a provider and evaluations.'],
['MCP / APIs','Implemented foundation','Read-only catalogue MCP; authenticated internal APIs. Enterprise external OAuth and write tools are deferred.'],
['SEO','Private staging','Server-rendered routes, metadata and language alternates. Indexing disabled until public launch approval.'],
['Social marketing','Configuration required','Campaign records, UTM builder and share links; automatic posting, analytics and spending remain disconnected.'],
['Customer photos','Implemented control','Optional separate permission; private scoped attachments; no facial recognition or public gallery.'],
['Commerce / billing','Scope capture only','Quotations capture need; payment, subscriptions, tax, contracts and recurring billing are not activated.'],
['Governance / production assurance','Further work required','Source register and audits implemented; penetration, accessibility, restore, full SSO and integration acceptance gates remain.']
];
