import {getDb} from '@/db';
import {getCurrentUser} from '@/lib/auth';
import {SITE_URL} from '@/lib/site';
export {SITE_URL};
export const runtime=()=>process.env as unknown as Record<string,any>;
export function db(){return getDb();}
export const now=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export async function identity(){const u=await getCurrentUser();return u?{id:u.id,email:u.email.toLowerCase(),displayName:u.displayName}:null;}
export function isAdmin(email:string){return String(runtime().ADMIN_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).filter(Boolean).includes(email.toLowerCase());}
export async function ensureRoot(){await db().prepare("INSERT INTO tenants (id,name,locale,brand,created_at) VALUES ('daffodil','Daffodil AI','en','Daffodil AI',?) ON CONFLICT(id) DO NOTHING").bind(now()).run();}
export async function bootstrap(user:NonNullable<Awaited<ReturnType<typeof identity>>>){if(!isAdmin(user.email))return;await ensureRoot();await db().prepare("INSERT INTO memberships (id,tenant_id,email,user_id,role,created_at) VALUES (?,'daffodil',?,?,'Owner',?) ON CONFLICT(tenant_id,email) DO NOTHING").bind(uid(),user.email,user.id,now()).run();}
export const canWrite=(role:string,kind:string)=>role==='Owner'||role==='Admin'||(role==='Sales'&&['leads','opportunities','meetings','exhibitors','tasks','tickets'].includes(kind))||(role==='Editor'&&['research','content','campaigns','automation'].includes(kind))||(role==='Support'&&['tickets','tasks'].includes(kind));
export const canRead=(role:string,kind:string)=>role==='Owner'||role==='Admin'||role==='Viewer'||(role==='Sales'&&['leads','opportunities','meetings','exhibitors','staff','tasks','tickets'].includes(kind))||(role==='Editor'&&['research','content','campaigns','automation'].includes(kind))||(role==='Support'&&['tickets','tasks'].includes(kind));
export async function authorize(tenantId:string,kind:string,write=false){const user=await identity();if(!user)throw new HttpError(401,'Sign in to continue.');const member=await db().prepare('SELECT * FROM memberships WHERE tenant_id=? AND email=?').bind(tenantId,user.email).first();if(!member||!(write?canWrite(member.role,kind):canRead(member.role,kind)))throw new HttpError(403,'This organization or action is outside your assigned access.');return {user,member};}
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export function ok(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export function fail(e:unknown){if(e instanceof HttpError)return ok({error:e.message},e.status);console.error('Daffodil request failed',e instanceof Error?e.message:'Unknown failure');return ok({error:'The service could not complete this request. Please try again.'},503);}
export function csrf(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin&&origin!==SITE_URL)throw new HttpError(403,'Request origin is not allowed.');if(!origin&&req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Cross-site request is not allowed.');}
export async function body(req:Request){csrf(req);const text=await req.text();if(text.length>40000)throw new HttpError(413,'Request is too large.');try{return JSON.parse(text)}catch{throw new HttpError(400,'Invalid request format.');}}
export function auditStatement(tenant:string,actor:string,action:string,entity:string,summary:string){return db().prepare('INSERT INTO audit (id,tenant_id,actor,action,entity_id,summary,created_at) VALUES (?,?,?,?,?,?,?)').bind(uid(),tenant,actor,action,entity,summary,now());}
export async function limit(req:Request,key:string,max:number){const day=new Date().toISOString().slice(0,13);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode((req.headers.get('cf-connecting-ip')||'anonymous')+day+key));const id=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');const row=await db().prepare('INSERT INTO rate_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id,new Date(Date.now()+7200000).toISOString()).first();if(row.count>max)throw new HttpError(429,'Too many requests. Please try again later.');await db().prepare('DELETE FROM rate_limits WHERE expires < ?').bind(now()).run();}
